#!/bin/bash
cp -i templates/FREEIPA_EJABBER_LDAP_FILTER FREEIPA_EJABBER_LDAP_FILTER
cp -i templates/FREEIPA_EJABBER_LDAP_ROOTDN FREEIPA_EJABBER_LDAP_ROOTDN
cp -i templates/FREEIPA_EJABBER_LDAP_BASE FREEIPA_EJABBER_LDAP_BASE
FREEIPA_TLD=$(cat FREEIPA_TLD)
FREEIPA_SLD=$(cat FREEIPA_SLD)
sed -i "s/REPLACEME_TLD/$FREEIPA_TLD/g" FREEIPA_EJABBER_LDAP_FILTER
sed -i "s/REPLACEME_SLD/$FREEIPA_SLD/g" FREEIPA_EJABBER_LDAP_FILTER
sed -i "s/REPLACEME_TLD/$FREEIPA_TLD/g" FREEIPA_EJABBER_LDAP_ROOTDN
sed -i "s/REPLACEME_SLD/$FREEIPA_SLD/g" FREEIPA_EJABBER_LDAP_ROOTDN
sed -i "s/REPLACEME_TLD/$FREEIPA_TLD/g" FREEIPA_EJABBER_LDAP_BASE
sed -i "s/REPLACEME_SLD/$FREEIPA_SLD/g" FREEIPA_EJABBER_LDAP_BASE
