#!/bin/bash
cp -i templates/EJABBER_LDAP_FILTER FREEIPA_EJABBER_LDAP_FILTER
cp -i templates/EJABBER_LDAP_ROOTDN FREEIPA_EJABBER_LDAP_ROOTDN
cp -i templates/EJABBER_LDAP_BASE FREEIPA_EJABBER_LDAP_BASE
cp -i templates/IPA_SERVER_INSTALL_OPTS IPA_SERVER_INSTALL_OPTS
FREEIPA_TLD=$(cat FREEIPA_TLD)
FREEIPA_SLD=$(cat FREEIPA_SLD)
REPLACEME_DATE_I=$(date +%Y%m%d%H%M%S)
sed -i "s/REPLACEME_TLD/$FREEIPA_TLD/g" FREEIPA_EJABBER_LDAP_FILTER
sed -i "s/REPLACEME_SLD/$FREEIPA_SLD/g" FREEIPA_EJABBER_LDAP_FILTER
sed -i "s/REPLACEME_TLD/$FREEIPA_TLD/g" FREEIPA_EJABBER_LDAP_ROOTDN
sed -i "s/REPLACEME_SLD/$FREEIPA_SLD/g" FREEIPA_EJABBER_LDAP_ROOTDN
sed -i "s/REPLACEME_TLD/$FREEIPA_TLD/g" FREEIPA_EJABBER_LDAP_BASE
sed -i "s/REPLACEME_SLD/$FREEIPA_SLD/g" FREEIPA_EJABBER_LDAP_BASE
sed -i "s/REPLACEME_DATE_I/$REPLACEME_DATE_I/g" IPA_SERVER_INSTALL_OPTS
